name = "rds-live-extractor"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# KV namespace for caching
[[kv_namespaces]]
binding = "RDS_CACHE"
id = "2d108657f24543f484455cc178078006"  # Replace with actual KV namespace ID
preview_id = "ccdb4b2806fe4f808bb737cb0253418f"  # Replace with preview namespace ID

# Scheduled trigger - runs every 1h45min
[triggers]
crons = ["*/2 * * * *"]  # Every 2 minutes

# Environment variables (optional)
[vars]
ENVIRONMENT = "production"

# Worker limits and settings
[build]
command = ""

[env.staging]
name = "rds-live-extractor-staging"
vars = { ENVIRONMENT = "staging" }

[[env.staging.kv_namespaces]]
binding = "RDS_CACHE"
id = "YOUR_STAGING_KV_NAMESPACE_ID"
preview_id = "YOUR_STAGING_KV_PREVIEW_ID"
